version: "3.7"
services:
  app:
    build:
      args:
        user: xavier_igor
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: avaliacao_vx
    container_name: avaliacao_vx-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - avaliacao_vx

  db:
    image: "mysql:5.7"
    container_name: avaliacao_vx-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - avaliacao_vx
    ports:
      - "3306:3306"
    
  nginx:
    image: nginx:alpine
    container_name: avaliacao_vx-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - avaliacao_vx

networks:
  avaliacao_vx:
    driver: bridge
