version: "3.7"
services:
  app:
    build:
      args:
        user: xavier_igor
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: Avaliacao_VX
    container_name: Avaliacao_VX-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - Avaliacao_VX

  db:
    image: mysql:5.7
    container_name: Avaliacao_VX-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - Avaliacao_VX
      ports:
        - "3306:3306"

  nginx:
    image: nginx:alpine
    container_name: Avaliacao_VX-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - Avaliacao_VX

networks:
  travellist:
    driver: bridge